services:
  - type: web
    name: resumeai-analyzer
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 4 --threads 2 --worker-class gthread --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///resume_analyzer.db
      - key: GROQ_API_KEY
        sync: false # This prevents your actual key from being committed. Render will prompt you to enter it in their dashboard.